### ISSUE TITLE
F-Droid recommends uninstalling! ☹️

### ISSUE THREAD

**Issue by gelin** [gelin/open-in-browser#12]
**[Original report](https://bitbucket.org/gelin/open-in-browser/issue/12) by TP S (Bitbucket: [T_P_S](https://bitbucket.org/T_P_S), ).**

----------------------------------------

@gelin:
![Screenshot_20180423-002910.png](https://bitbucket.org/repo/X9Bx7n/images/2609799917-Screenshot_20180423-002910.png)

**Comment by gelin** [comment]
**Original comment by Denis Nelubin (Bitbucket: [gelin](https://bitbucket.org/gelin), GitHub: [gelin](https://github.com/gelin)).**

----------------------------------------

F-Droid doesn't answer by email. Created the topic in their forum:
https://forum.f-droid.org/t/open-in-browser-silently-removed-from-f-droid/2668

**Comment by gelin** [comment]
**Original comment by Denis Nelubin (Bitbucket: [gelin](https://bitbucket.org/gelin), GitHub: [gelin](https://github.com/gelin)).**

----------------------------------------

Updated the app a bit. Added new tag. Will see what F-Droid will do with it.

**Comment by TPS** [comment]
@gelin Just found my report here (you could probably update my nickname above).  I think this is resolved, as I no longer see any kind of warning when trying to install this.

However, I don't think F-Droid is tracking the GitHub repo, as all this listing's links _still_ point to BitBucket: no updates are being caught, so I've opened [an accepted merge request to update that](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6720).

**Comment by gelin** [comment]
@TPS Thanks a lot!
